### PR TITLE
fix link to elixir website

### PR DESCRIPTION
**Pull request by shalecraig**
`http://http://elixir-lang.org/` -> `http://elixir-lang.org/`

### CODE REVIEW

**Comment by shalecraig** [comment]
Not sure what happened with the last line

**Comment by KronicDeth** [comment]
Well, that's just an embarrassing typo.  Thanks for the fix.

**Comment by KronicDeth** [comment]
The last line was your editor inserting a newline at the end of the file.  The README didn't have one before.

**Comment by shalecraig** [comment]
Thanks for the merge. I was more confused the github diff didn't have any indicator of whitespace at EOF changes.

**Pull request merged**
