### PR TITLE
Debugger implementation supporting line breakpoints

### PR DESCRIPTION
**Pull request by JakeBecker**
It's still rough around the edges, but the basics work! :)

screen shot 2017-03-13 at 3 58 50 pm

### CODE REVIEW

**Comment by KronicDeth** [comment]
@JakeBecker I can't breakpoint in ExUnit `.exs` files.  Is that to be expected because they won't make `.beam` files?

**Comment by KronicDeth** [comment]
```
11:08:20.430 [error] Process #PID<0.312.0> raised an exception
** (ArgumentError) argument error
    (stdlib) erl_anno.erl:318: :erl_anno.set(:location, -1, [location: -1, generated: true])
```

With Elixir 1.3.4.  I'll have to try it with Elixir 1.4.X.

**Comment by KronicDeth** [comment]
No, same problem on Elixir 1.4.2 with erl_anno and -1.

**Comment by JakeBecker** [comment]
@KronicDeth, the inability to set breakpoints in .exs files is expected for now, but I think it's not insurmountable. I think it should be possible to set breakpoints (so long as they're within modules), but the exs file needs to be loaded first so it can define the modules, and the current code makes no provision for that. My inclination is to leave it for future versions unless it seems easy to tackle.

**Comment by KronicDeth** [comment]
`erl_anno` bug comments I found:
* https://github.com/elixir-lang/elixir/issues/4617#issuecomment-220882960
* https://github.com/elixir-lang/elixir/issues/5641#issuecomment-271630880
  * This seems to indicate that I need to be on a newer version of dependencies that don't use line -1 when on Erlang 19.

**Comment by KronicDeth** [comment]
Got it working using reflection in 14.X and C-S-D/calcinator

screen shot 2017-04-21 at 9 37 32 pm

**Comment by KronicDeth** [comment]
Something to fix later, it appears to spew the debugger packets to stdout:

```
*DBG* 'Elixir.IntellijElixir.DebugServer' got {tcp,#Port<0.36663>,
                                               <<131,104,2,100,0,9,115,116,
                                                 101,112,95,105,110,116,111,
                                                 103,100,0,13,110,111,110,111,
                                                 100,101,64,110,111,104,111,
                                                 115,116,0,0,5,95,0,0,0,0,0>>}
```

**Comment by KronicDeth** [comment]
@JakeBecker did you mean commit the compiled `*.beam` files for the debugger?  Don't we need to rebuild those whenever the user switches the SDK to ensure the `.beam` is Erlang and Elixir version compatible?

**Comment by jlirochon** [comment]
Awesome awesomeness !

Thank you @JakeBecker , thank you @KronicDeth !

**Comment by JakeBecker** [comment]
@KronicDeth big thanks for fixing up that PR, I know that must have been a pain. To answer your earlier questions:
- I committed the beam files just because I was a bit too lazy to add it to the build script, but I agree that'd be better.
- Good catch on the debugging trace spewing output, that can get disabled.

**Pull request merged**
