### PR TITLE
Support Jetbrains 2024.3 (243.21565.193)

### PR DESCRIPTION
**Pull request by joshuataylor**
https://youtrack.jetbrains.com/articles/IDEA-A-2100662289/IntelliJ-IDEA-2024.3-243.21565.193-build-Release-Notes

### CODE REVIEW

**Comment by jmSfernandes** [comment]
The new version of InteliJ just droped yesterday :) 
Is there plans to merge this one? 

----
Thanks for all you hard work, really love this plugin <3

**Comment by joshuataylor** [comment]
Yep, didn't realise it dropped!

I'll get it tested and merged ASAP.

**Comment by joshuataylor** [comment]
https://github.com/KronicDeth/intellij-elixir/releases/tag/v20.0.0

**Comment by SamuelGaona** [comment]
Not working on WebStorm 2024.3
image

**Comment by joshuataylor** [comment]
Annoying! I will double check versions across their IDEs, and submit another build with the fixed versions.

Thanks for letting us know!

**Comment by Kae-Tempest** [comment]
Hello ! Can you update the plugin for Webstorm ? can't update to v20

**Comment by joshuataylor** [comment]
Will be supported in 20.0.1

https://github.com/KronicDeth/intellij-elixir/pull/3667

**Comment by joshuataylor** [comment]
Can you try the 20.0.1 release, it will be available once JetBrains has approved it. Given it's the weekend, it'll probably be next week.

You can use the .zip here @Kae-Tempest https://github.com/KronicDeth/intellij-elixir/releases/tag/v20.0.1

**Pull request merged**
