### PR TITLE
Remove unnecessary IDE configuration files

### PR DESCRIPTION
**Pull request by JakeBecker**
@KronicDeth Thanks for merging the Gradle changes. I think, though, that it'd be a good idea to remove most of the IDE configuration files from `.idea`. When I check out a fresh copy of the project and try to open it in the IDE, it fails to find the SDK because `misc.xml` specifies it as `IntelliJ IDEA Community Edition IC-145.258.1` which does not exist on my system. It looks like I would need to use an Intellij Idea Platform SDK instead of a regular JDK, and I'd have to name it the same as you did to avoid conflicts in `misc.xml`.

I think it's easier for other people to contribute if the `.idea` directory only includes `runConfigurations`, as in the [Rust plugin](https://github.com/intellij-rust/intellij-rust/tree/master/.idea). Intellij's auto-import of Gradle projects works very well, and this way we wouldn't risk conflicts when developers change their IDE settings or use different versions of the IDE.

### CODE REVIEW

**Comment by KronicDeth** [comment]
I think there needs to be some sort of compromise where we don't include the SDK, but we do include the modules because otherwise the source files themselves are kinda unusable without a lot of manual configuration.  I included the modules because in addition to needing to setup the SDK a lot of the features for Java in IntelliJ don't work until you Mark Directory and those module files include those marks, such as Resource, Test Source, Source, and Generated.  I'd like to be able to distribute those directory marks and not pick the SDK if that's possible, otherwise all contributors need to setup those marks for IntelliJ to properly show the tests can be run as tests in the context menu, etc.

**Comment by JakeBecker** [comment]
I'm using Intellij 2016.3, and it looks to me like it handles marking root directories correctly. Here's a screenshot after importing the Gradle project without the IDE configuration files:

screen shot 2017-03-09 at 5 21 54 pm

**Comment by KronicDeth** [comment]
Ok, I saw some screwy behaviour when I was trying your #504 branch, but maybe it's an issue with switching branches and not reopening the project.  I'll try out this branch by switching outside of IntelliJ and then opening it fresh.

**Comment by JakeBecker** [comment]
Not sure if it makes a difference, but these are the settings I used to import it: 
screen shot 2017-03-09 at 5 29 26 pm

**Comment by JakeBecker** [comment]
I updated `CONTRIBUTING.md` and included some screenshots. I also added run configurations for `test` and `runIde` that don't override the `ideaVersion` from `gradle.properties`. Those should probably be what is used for most development, since the IDE will auto-import that version of the dependency, and things might get screwy if someone tries to set a breakpoint in them but a different version is loaded when they actually run it.

**Pull request merged**
