### PR TITLE
2024.1 minor update

### PR DESCRIPTION
**Pull request by noizu**
- Update until-version to 421,
- Update Intellij to 2024.1
- Add note in Contributing on building only the plugin as I spent too long like and idiot installing the wrong jar ;)

### CODE REVIEW

**Comment by billylaing** [comment]
Thanks @noizu! It has been working perfectly for me.

**Comment by rNoz** [comment]
I am trying to build this locally, following the CONTRIBUTING guide (really outdated based on recent IDEs), but somehow it fails at :jps-shared:compileJava. Can I know which versions are you using? gradle/java.

```
> Task :jps-shared:initializeIntelliJPlugin
Caching disabled for task ':jps-shared:initializeIntelliJPlugin' because:
  Build cache is disabled
Task ':jps-shared:initializeIntelliJPlugin' is not up-to-date because:
  Task state is not tracked.
[gradle-intellij-plugin :jps-shared jps-shared] Build feature is enabled: org.jetbrains.intellij.buildFeature.selfUpdateCheck
[gradle-intellij-plugin] Resolving Gradle IntelliJ Plugin version with: jar:file:/home/user/projects/jetbrains/gradle-7.4.2/caches/jars-9/276a83a09929b44da50eaeaabc425796/gradle-intellij-plugin-1.13.3.jar!/META-INF/MANIFEST.MF
:jps-shared:initializeIntelliJPlugin (Thread[Execution worker for ':',5,main]) completed. Took 0.044 secs.
:jps-shared:patchPluginXml (Thread[Execution worker for ':',5,main]) started.

> Task :jps-shared:patchPluginXml NO-SOURCE
Skipping task ':jps-shared:patchPluginXml' as it has no source files and no previous output files.
:jps-shared:patchPluginXml (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:jps-shared:verifyPluginConfiguration (Thread[Execution worker for ':',5,main]) started.

> Task :jps-shared:verifyPluginConfiguration
Caching disabled for task ':jps-shared:verifyPluginConfiguration' because:
  Build cache is disabled
Task ':jps-shared:verifyPluginConfiguration' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
:jps-shared:verifyPluginConfiguration (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:jps-shared:compileJava (Thread[Execution worker for ':',5,main]) started.

The input changes require a full rebuild for incremental task ':jps-shared:compileJava'.
Full recompilation is required because no incremental change information is available. This is usually caused by clean builds or changing compiler arguments.
Compiling with toolchain '/usr/lib/jvm/java-11-openjdk'.
file or directory '/home/user/jetbrains/intellij-elixir-noizu/jps-shared/src/main/java', not found
...
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
```

What I have tried:
- clean + full recompilation.
- Also, both using the shell `./gradlew buildPlugin` and also from intellij-idea.
- using java8 and java11.
- Gradle fetched manually and located in a dir (7.4.2), but also with Intellij-IDEA Gradle plugin and Gradle in settings.

**Comment by noizu** [comment]
i am building with asdf with versions from .tool-versions.

**Comment by rNoz** [comment]
Great, now it works! Thanks. Testing the plugin for an hour.

**Comment by noizu** [comment]
> Doesn't work (can't set SDKs) because it just naively bumps versions without addressing plugin API changes. This is duplicated effort of #3569 that works.

I mean you say that but it works fine on my intellij.

**Pull request closed without merging**
