### PR TITLE
Support 233 IDEA (2023.3 release)

### PR DESCRIPTION
**Pull request by joshuataylor**
Ah the march of time. Seems this should be fairly painless upgrade, so thought I'd start the ball rolling and post here.

Feel free to change anything :).

I also get an error when running `./gradle test`:

```
Unable to load JUnit4 runner to calculate Ignored test cases
```

Full log:
https://gist.github.com/joshuataylor/92e232fb11dee51546353994721a06de

### CODE REVIEW

**Comment by Waynenabors** [comment]
@joshuataylor thanks for starting this, I had to bump gradle to `7.6.1` for some reason, but have it working on Mac OS 14 and RubyMine 2023.3

**Comment by StragaSevera** [comment]
Now that 2023.3 is released, when this PR will be merged? @KronicDeth

**Comment by jmSfernandes** [comment]
Thanks, so much for the hard work on this plugin.
When can we expect the release of the new version?

**Comment by StragaSevera** [comment]
Can somebody, please, manually build this version, if it is hard to release it officially?

**Comment by allenwyma** [comment]
> Can somebody, please, manually build this version, if it is hard to release it officially?

You can get the pre-release version. There's instructions on the README. That's what I'm using.

**Pull request merged**
